# Seudo code
def initial():
  agent -
    susceptible
      - 'vaccines'
    state
      (SEIR)

  network
    - full mixed
    - structure, complex network - small world

    - separation ~SEIR

def simulate():
  random walk ()
  '''agent to agent ~ network, 
  infected? ~ distribution'''

  stopFunction():
  '''-1 stable
  -2 set a time'''

def output():
  statistic()
    - 3 curves
    - people contact frequency

initial()

simulate()

output()

---

In [ ]:
# sort for two different network

In [1]:
import numpy as np
import pandas as pd

In [11]:
def initial(agentNum=1000):
    # the default agentNum is 1000
    
    # try-except: catch error when agent number is illegal (e.g. not int, negative)
    
    infectedList = np.zeros(agentNum)
    
    # SEIR model
    susceptState = np.zeros(agentNum)
    exposedState = np.zeros(agentNum)
    infectState = np.zeros(agentNum)
    
    
    susceptList = np.random.lognormal(mean=4.5, sigma=1.5, size=agentNum)
    symptomList = np.random.lognormal(mean=1.1, sigma=0.9, size=agentNum)
    
    print(agentNum)
    
    return(infectedList, susceptList, symptomList)

In [12]:
def initialNetwork():
    myNetwork = []

    print('This is the initialNetwork function')
    # draw the network
    return(myNetwork)

In [13]:
def simulate(myNetwork = [], infectedList = [], 
             susceptList = [], symptomList = []):
    
    # try-except: check input
    if sum([ 1 for i in [myNetwork, infectedList, susceptList, symptomList] if not i ]):
        print('There are empty list in the input, please check')
    
    #
    myTime = []
    susRatio = []
    exposeRatio = []
    infecRatio = []
    recoverRatio = []
    interactionRatio = []
    
    print('This is the simulate function')
    return(myTime, 
           susRatio, exposeRatio, infecRatio, recoverRatio,
           interactionRatio)
    

In [14]:
def output(myTime=[], 
           susRatio=[], exposeRatio=[], infecRatio=[], recoverRatio=[],
           interactionRatio=[]):
    
    if sum([ 1 for i in [myTime, susRatio, exposeRatio, infecRatio, recoverRatio, interactionRatio] if not i ]):
        print('There are empty list in the input, please check')
    
    # demo data
    myTime=[i for i in range(100)] 
    susRatio=[i/100 for i in range(100)]
    exposeRatio=[i/100 for i in range(100)] 
    infecRatio=[i/100 for i in range(100)] 
    recoverRatio=[i/100 for i in range(100)] 
    interactionRatio=[i/100 for i in range(100)] 
    
    print('This is the output function')
    # to draw some plot

In [15]:
initial(agentNum = 10)

10


(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([ 136.72434344,   91.67602726,   48.86138806,   10.34763226,
         573.25153736, 1056.65057546,  175.38678654,    2.66110057,
         655.95363127,   46.75069247]),
 array([ 6.20690684,  5.09489173,  3.79623154, 12.63653312,  0.99885344,
         2.96632518,  2.63400463,  9.34965085,  2.97714778,  3.46847581]))

In [16]:
initialNetwork()

This is the initialNetwork function


[]

In [8]:
simulate()

There are empty list in the input, please check
This is the simulate function


([], [], [], [], [], [])

In [9]:
sum([ 1 for i in [[1], [1], [1], [1]] if not i ])

0

In [10]:
output()

There are empty list in the input, please check
This is the output function
