# Seudo code
def initial():
  agent -
    susceptible
      - 'vaccines'
    state
      (SEIR)

  network
    - full mixed
    - structure, complex network - small world

    - separation ~SEIR

def simulate():
  random walk ()
  '''agent to agent ~ network, 
  infected? ~ distribution'''

  stopFunction():
  '''-1 stable
  -2 set a time'''

def output():
  statistic()
    - 3 curves
    - people contact frequency

initial()

simulate()

output()

---

In [1]:
import numpy as np
import pandas as pd

In [2]:
def initial(agentNum=1000):
    # the default agentNum is 1000
    
    # try-except: catch error when agent number is illegal (e.g. not int, negative)
    
    infectedList = np.ones(agentNum)
    susceptList = np.random.lognormal(mean=4.5, sigma=1.5, size=agentNum)
    symptomList = np.random.lognormal(mean=1.1, sigma=0.9, size=agentNum)
    
    print(agentNum)
    
    return(infectedList, susceptList, symptomList)

In [3]:
def initialNetwork():
    myNetwork = []

    print('This is the initialNetwork function')
    # draw the network
    return(myNetwork)

In [4]:
def simulate(myNetwork = [], infectedList = [], 
             susceptList = [], symptomList = []):
    
    # try-except: check input
    if sum([ 1 for i in [myNetwork, infectedList, susceptList, symptomList] if not i ]):
        print('There are empty list in the input, please check')
    
    #
    myTime = []
    susRatio = []
    exposeRatio = []
    infecRatio = []
    recoverRatio = []
    interactionRatio = []
    
    print('This is the simulate function')
    return(myTime, 
           susRatio, exposeRatio, infecRatio, recoverRatio,
           interactionRatio)
    

In [5]:
def output(myTime=[], 
           susRatio=[], exposeRatio=[], infecRatio=[], recoverRatio=[],
           interactionRatio=[]):
    
    if sum([ 1 for i in [myTime, susRatio, exposeRatio, infecRatio, recoverRatio, interactionRatio] if not i ]):
        print('There are empty list in the input, please check')
    
    # demo data
    myTime=[i for i in range(100)] 
    susRatio=[i/100 for i in range(100)]
    exposeRatio=[i/100 for i in range(100)] 
    infecRatio=[i/100 for i in range(100)] 
    recoverRatio=[i/100 for i in range(100)] 
    interactionRatio=[i/100 for i in range(100)] 
    
    print('This is the output function')
    # to draw some plot

In [6]:
initial(agentNum = 10)

10


(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([ 94.82741844, 130.04278713, 147.11605863,  93.69746156,
         37.2550447 , 176.97276369, 596.46251409,  31.98766656,
         22.32638126, 100.47937239]),
 array([ 2.87790115,  1.09344662,  2.16754671,  2.30419877,  1.67980765,
         3.38876589,  5.11714197, 16.67525614,  1.42423565,  2.23735635]))

In [7]:
initialNetwork()

This is the initialNetwork function


[]

In [8]:
simulate()

There are empty list in the input, please check
This is the simulate function


([], [], [], [], [], [])

In [9]:
sum([ 1 for i in [[1], [1], [1], [1]] if not i ])

0

In [10]:
output()

There are empty list in the input, please check
This is the output function
