# Seudo code
def initial():
  agent -
    susceptible
      - 'vaccines'
    state
      (SEIR)

  network
    - full mixed
    - structure, complex network - small world

    - separation ~SEIR

def simulate():
  random walk ()
  '''agent to agent ~ network, 
  infected? ~ distribution'''

  stopFunction():
  '''-1 stable
  -2 set a time'''

def output():
  statistic()
    - 3 curves
    - people contact frequency

initial()

simulate()

output()

---

In [5]:
import numpy as np
import pandas as pd

In [6]:
def initial(agentNum=1000):
    # the default agentNum is 1000
    
    # try-except: catch error when agent number is illegal (e.g. not int, negative)
    
    infectedList = np.ones(agentNum)
    susceptList = np.random.lognormal(mean=4.5, sigma=1.5, size=agentNum)
    symptomList = np.random.lognormal(mean=1.1, sigma=0.9, size=agentNum)
    
    print(agentNum)
    
    return(infectedList, susceptList, symptomList)

In [11]:
def initialNetwork():
    myNetwork = []

    print('This is the initialNetwork function')
    # draw the network
    return(myNetwork)

In [27]:
def simulate(myNetwork = [], infectedList = [], 
             susceptList = [], symptomList = []):
    
    # try-except: check input
    if sum([ 1 for i in [myNetwork, infectedList, susceptList, symptomList] if not i ]):
        print('There are empty list in the input, please check')
    
    #
    myTime = []
    susRatio = []
    exposeRatio = []
    infecRatio = []
    recoverRatio = []
    interactionRatio = []
    
    print('This is the simulate function')
    return(myTime, 
           susRatio, exposeRatio, infecRatio, recoverRatio,
           interactionRatio)
    

In [33]:
def output(myTime=[], 
           susRatio=[], exposeRatio=[], infecRatio=[], recoverRatio=[],
           interactionRatio=[]):
    
    if sum([ 1 for i in [myTime, susRatio, exposeRatio, infecRatio, recoverRatio, interactionRatio] if not i ]):
        print('There are empty list in the input, please check')
    
    print('This is the output function')
    # to draw some plot

In [9]:
initial(agentNum = 10)

10


(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([459.49039206, 158.79003603, 444.02385987,  78.97374103,
        879.58810342,  75.08740306, 212.88163172, 347.64678386,
         99.73435572, 170.97807544]),
 array([ 1.66032609, 13.60940023,  2.59795831,  9.32772996,  7.96876338,
         3.49884288,  5.93621325,  1.74233794,  2.09706125,  2.94760045]))

In [29]:
initialNetwork()

This is the initialNetwork function


[]

In [28]:
simulate()

There are empty list in the input, please check
This is the simulate function


([], [], [], [], [], [])

In [26]:
sum([ 1 for i in [[1], [1], [1], [1]] if not i ])

0

In [31]:
output()

TypeError: output() missing 6 required positional arguments: 'myTime', 'susRatio', 'exposeRatio', 'infecRatio', 'recoverRatio', and 'interactionRatio'